{
  "services": [
    {
      "type": "web",
      "name": "cubeplus-trading-simulator",
      "env": "python",
      "buildCommand": "pip install -r requirements.txt",
      "startCommand": "gunicorn -c gunicorn.conf.py wsgi:app",
      "envVars": [
        {
          "key": "TRADEJINI_APIKEY",
          "value": "your_api_key_here"
        },
        {
          "key": "TRADEJINI_PASSWORD",
          "value": "your_password_here"
        },
        {
          "key": "TRADEJINI_TWO_FA",
          "value": "123456"
        },
        {
          "key": "TRADEJINI_TWO_FA_TYPE",
          "value": "TOTP"
        },
        {
          "key": "DATABASE_URL",
          "value": "sqlite:///app.db"
        },
        {
          "key": "SECRET_KEY",
          "value": "your-secret-key-change-this"
        }
      ]
    }
  ]
}